#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        web: debug
#    org.springframework.web.servlet: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/main022?serverTimezone=Asia/Seoul
#    username: root
#    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  redis:
#    host: localhost  # 배포 시 ec2 주소 사용
#    port: 6379


jwt:
  key: abcd123456789123456789123456789abcdabcd
  access-token-expiration-minutes: 30000
  refresh-token-expiration-minutes: 30000

mail:
  address:
    admin: admin@gmail.com