#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#    org.springframework.web.servlet: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace


cloud:
  aws:
    credentials:
      access-key: AKIAXBFDN3IW3QG43QGG
      secret-key: 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
    s3: #버킷이름
      bucket: codemain022
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  #  servlet:
  #    multipart:
  #      max-file-size: 10MB
  #      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://database-1.cyfntkyjd4c0.ap-northeast-2.rds.amazonaws.com:13306/main?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: admin1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    log-request-details: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            clientSecret: ${GoogleClientSecret}
#            scope:
#              - email
#              - profile
#  sql.init.mode: always
mail:
  address:
    admin: admin@admin
jwt:
  key: abcd123456789123456789123456789abcdabcd
  access-token-expiration-minutes: 480
  refresh-token-expiration-minutes: 900

image:
  upload:
    dir : classpath:/static/images/