import { atom } from "recoil";

export const keywordsAtom = atom({
  key: "keywords",
  default: [
    "중식",
    "한식",
    "일식",
    "양식",
    "분식",
    "매운거",
    "안매운거",
    "아이와 함께",
    "데이트",
    "랜덤",
  ],
});
export const storesState = atom({
  key: "restaurant",
  default: [
    {
      id: 1,
      name: "호미스피자1",
      photo: "/logo192.png",
      introduction:
        "안녕하세요. 호미스피자입니다. 저희는 2012년 론칭한 브랜드로 COOL한 당신에게 HOT한 피자로 보답해드립니다!",
      reviews: 50,
      favorites: 25,
      tags: ["한식", "고기"],
      isFavorite: false,
      createdDate: "2023-01-01",
    },
    {
      id: 2,
      name: "피자글릭",
      photo: "/logo192.png",
      introduction:
        "행복을 토핑하다 소스바르는것부터 토핑까지 정성으로 만들어 한입만 드셔보면, 눈이 번쩍뜨이는 피자글릭입니다~^^",
      reviews: 30,
      favorites: 15,
      tags: ["중식", "매운음식"],
      isFavorite: true,
      createdDate: "2023-02-15",
    },
    {
      id: 3,
      name: "이탈리안 다린",
      photo: "/logo192.png",
      introduction:
        "이탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 4,
      name: "호미스피자444",
      photo: "/logo192.png",
      introduction:
        "4444 저희는 2012년 론칭한 브랜드로 COOL한 당신에게 HOT한 피자로 보답해드립니다!",
      reviews: 50,
      favorites: 25,
      tags: ["한식", "고기"],
      isFavorite: false,
      createdDate: "2023-01-01",
    },
    {
      id: 5,
      name: "피자글릭5555",
      photo: "/logo192.png",
      introduction:
        "555555스바르는것부터 토핑까지 정성으로 만들어 한입만 드셔보면, 눈이 번쩍뜨이는 피자글릭입니다~^^",
      reviews: 30,
      favorites: 15,
      tags: ["중식", "매운음식"],
      isFavorite: true,
      createdDate: "2023-02-15",
    },
    {
      id: 6,
      name: "이탈리안 다린666",
      photo: "/logo192.png",
      introduction:
        "6666 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 7,
      name: "호미77스피77자",
      photo: "/logo192.png",
      introduction:
        "7777 자입니다. 저희는 2012년 론칭한 브랜드로 COOL한 당신에게 HOT한 피자로 보답해드립니다!",
      reviews: 50,
      favorites: 25,
      tags: ["한식", "고기"],
      isFavorite: false,
      createdDate: "2023-01-01",
    },
    {
      id: 8,
      name: "피8자8글8릭8",
      photo: "/logo192.png",
      introduction:
        "행복을 88888토핑하다 소스바르는것부터 토핑까지 정성으로 만들어 한입만 드셔보면, 눈이 번쩍뜨이는 피자글릭입니다~^^",
      reviews: 30,
      favorites: 15,
      tags: ["중식", "매운음식"],
      isFavorite: true,
      createdDate: "2023-02-15",
    },
    {
      id: 9,
      name: "이탈리안 9999다린",
      photo: "/logo192.png",
      introduction:
        "99999이탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 10,
      name: "호미10",
      photo: "/logo192.png",
      introduction:
        "10 자입니다. 저희는 2012년 론칭한 브랜드로 COOL한 당신에게 HOT한 피자로 보답해드립니다!",
      reviews: 50,
      favorites: 25,
      tags: ["한식", "고기"],
      isFavorite: false,
      createdDate: "2023-01-01",
    },
    {
      id: 11,
      name: "피11111111",
      photo: "/logo192.png",
      introduction:
        "행복을 1111토핑하다 소스바르는것부터 토핑까지 정성으로 만들어 한입만 드셔보면, 눈이 번쩍뜨이는 피자글릭입니다~^^",
      reviews: 30,
      favorites: 15,
      tags: ["중식", "매운음식"],
      isFavorite: true,
      createdDate: "2023-02-15",
    },
    {
      id: 12,
      name: "이탈리안 1212121212다린",
      photo: "/logo192.png",
      introduction:
        "12121212이탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 13,
      name: "호미13131313",
      photo: "/logo192.png",
      introduction:
        "133313131313 자입니다. 저희는 2012년 론칭한 브랜드로 COOL한 당신에게 HOT한 피자로 보답해드립니다!",
      reviews: 50,
      favorites: 25,
      tags: ["한식", "고기"],
      isFavorite: false,
      createdDate: "2023-01-01",
    },
    {
      id: 14,
      name: "151515151515",
      photo: "/logo192.png",
      introduction:
        "행복을151515토핑하다 소스바르는것부터 토핑까지 정성으로 만들어 한입만 드셔보면, 눈이 번쩍뜨이는 피자글릭입니다~^^",
      reviews: 30,
      favorites: 15,
      tags: ["중식", "매운음식"],
      isFavorite: true,
      createdDate: "2023-02-15",
    },
    {
      id: 15,
      name: "1515린",
      photo: "/logo192.png",
      introduction:
        "1515탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 16,
      name: "161161561616",
      photo: "/logo192.png",
      introduction:
        "16161616 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 17,
      name: "17171717",
      photo: "/logo192.png",
      introduction:
        "17171717탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 18,
      name: "1818",
      photo: "/logo192.png",
      introduction:
        "1818탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 19,
      name: "19",
      photo: "/logo192.png",
      introduction:
        "19요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 20,
      name: "20",
      photo: "/logo192.png",
      introduction:
        "20탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
    {
      id: 21,
      name: "21",
      photo: "/logo192.png",
      introduction:
        "1818탈리안 요리에서 찾는 약간의 즐거움과힐링 다린은 이탈리안 요리는 매일 새벽마다 직접 공수한 신선한 해산물과 재철 재료를 아끼지 않고 듬뿍 넣어 풍부한 맛을 느낄 수 있습니다.",
      reviews: 70,
      favorites: 1,
      tags: ["일식", "회"],
      isFavorite: true,
      createdDate: "2023-03-20",
    },
  ],
});
